version: '3.4'
services:
  test:
    build:
      context: .
      target: build-deps
    links:
      - mysql_legacy
      - mysql_replace_1
      - mysql_replace_2
      - mysql
      - pg
      - mssql
    command: ['npm', 'run', 'test:docker']
