version: '3.4'
services:
  test:
    build:
      context: .
      target: build-deps
    links:
      - mysql_legacy
      - mysql_replica_1
      - mysql_replica_2
      - mysql
      - pg
      - microsoftsql
    command: ['/start.sh']
